version: '3'

services:
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loveunicorns
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
    driver: local
  pg_data:
    driver: local